---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "isiwriter"  | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ print .Values.name "isiwriter"  | quote }}
subjects:
- kind: ServiceAccount
  name: {{ print "sa-ocd-" .Values.env  | quote }}
  namespace: {{ required "Missing required value project" .Values.project | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "isreader"  | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ print .Values.name "isreader"  | quote }}
subjects:
- kind: ServiceAccount
  name: {{ print "sa-ocd-" .Values.env  | quote }}
  namespace: {{ required "Missing required value project" .Values.project | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "istwriter"  | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ print .Values.name "istwriter"  | quote }}
subjects:
- kind: ServiceAccount
  name: {{ print "sa-ocd-" .Values.env  | quote }}
  namespace: {{ required "Missing required value project" .Values.project | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "iswriter"  | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ print .Values.name "iswriter"  | quote }}
subjects:
- kind: ServiceAccount
  name: {{ print "sa-ocd-" .Values.env  | quote }}
  namespace: {{ required "Missing required value project" .Values.project | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "sget"  | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ print .Values.name "sget"  | quote }}
subjects:
- kind: ServiceAccount
  name: {{ print "sa-ocd-" .Values.env  | quote }}
  namespace: {{ required "Missing required value project" .Values.project | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "dcwriter"  | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ print .Values.name "dcwriter"  | quote }}
subjects:
- kind: ServiceAccount
  name: get deploymentconfigs.apps.openshift.io
  namespace: {{ required "Missing required value project" .Values.project | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "dcreader"  | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ print .Values.name "dcreader"  | quote }}
subjects:
- kind: ServiceAccount
  name: get deploymentconfigs.apps.openshift.io
  namespace: {{ required "Missing required value project" .Values.project | quote }}
