apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "isiwriter"  | quote }}
rules:
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreamimports
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "isreader"  | quote }}
rules:
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "istreader"  | quote }}
rules:
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreamtags
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "istwriter"  | quote }}
rules:
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreamtags
  verbs:
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "iswriter"  | quote }}
rules:
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  verbs:
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "sget"  | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "dcwriter"  | quote }}
rules:
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "dcreader"  | quote }}
rules:
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "saget"  | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "bcget"  | quote }}
rules:
- apiGroups:
  - build.openshift.io
  resources:
  - buildconfigs
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ print .Values.name "bcpatch"  | quote }}
rules:
- apiGroups:
  - build.openshift.io
  resources:
  - buildconfigs
  verbs:
  - patch