---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ print .Values.env "isiwriter"  | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ print .Values.env "isiwriter"  | quote }}
subjects:
- kind: ServiceAccount
  name: {{ print "sa-ocd-" .Values.env  | quote }}
  namespace: {{ required "Missing required value project" .Values.project | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ print .Values.env "isreader"  | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ print .Values.env "isreader"  | quote }}
subjects:
- kind: ServiceAccount
  name: {{ print "sa-ocd-" .Values.env  | quote }}
  namespace: {{ required "Missing required value project" .Values.project | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ print .Values.env "istreader"  | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ print .Values.env "istreader"  | quote }}
subjects:
- kind: ServiceAccount
  name: {{ print "sa-ocd-" .Values.env  | quote }}
  namespace: {{ required "Missing required value project" .Values.project | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ print .Values.env "istwriter"  | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ print .Values.env "istwriter"  | quote }}
subjects:
- kind: ServiceAccount
  name: {{ print "sa-ocd-" .Values.env  | quote }}
  namespace: {{ required "Missing required value project" .Values.project | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ print .Values.env "iswriter"  | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ print .Values.env "iswriter"  | quote }}
subjects:
- kind: ServiceAccount
  name: {{ print "sa-ocd-" .Values.env  | quote }}
  namespace: {{ required "Missing required value project" .Values.project | quote }}
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   creationTimestamp: null
#   name: rcreadereng
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: rcreadereng
# subjects:
# - kind: ServiceAccount
#   name: {{ print "sa-ocd-" .Values.env  | quote }}
#   namespace: {{ required "Missing required value project" .Values.project | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ print .Values.env "sget"  | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ print .Values.env "sget"  | quote }}
subjects:
- kind: ServiceAccount
  name: {{ print "sa-ocd-" .Values.env  | quote }}
  namespace: {{ required "Missing required value project" .Values.project | quote }}
