apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ print .Values.env "isiwriter"  | quote }}
rules:
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreamimports
  verbs:
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ print .Values.env "isreader"  | quote }}
rules:
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ print .Values.env "istreader"  | quote }}
rules:
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreamtags
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ print .Values.env "istwriter"  | quote }}
rules:
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  verbs:
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ print .Values.env "iswriter"  | quote }}
rules:
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  verbs:
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ print .Values.env "sget"  | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  