repositories:
  - name: ocd-meta 
    url: https://ocd-scm.github.io/ocd-meta/charts
releases:
  - name: {{ requiredEnv "ENV_PREFIX" }}-ocd-webhook
    labels:
      webhook: realworld
    chart: ./ocd-environment-webhook
    version: ~1.1.0
    values:
      - tillerNamespace:  "{{ requiredEnv "TILLER_NAMESPACE" }}"
      - project: "{{ requiredEnv "PROJECT" }}"
      - insecureSkipTlsVerify: {{ env "INSECURE_NO_TLS_VERIFY" | default "false"  }}
      - hooksRelease: {{ env "HOOKS_RELEASE" | default "false"  }}
      - envGitUrl: "{{ requiredEnv "GIT_URL" }}"
      - webhookRepFullname: "{{ requiredEnv "GIT_NAME" }}"
      - webhookRefRegex: "{{ env "WEBHOOK_REF_REGEX" }}"
      - webhookSecret: "{{ env "WEBHOOK_SECRET" }}"
      - env: "{{ requiredEnv "ENV_PREFIX" }}"
      - deploy_env: 
        - name: OPENSHIFT_SERVER
          value: "{{ requiredEnv "OPENSHIFT_SERVER" }}"

