repositories:
  - name: ocd-meta 
    url: https://ocd-scm.github.io/ocd-meta/charts
releases:
  - name: {{ requiredEnv "ENV_PREFIX" }}-ocd-webhook
    labels:
      webhook: realworld
    chart: ./ocd-environment-webhook
    version: ~1.1.0
    values:
      - tillerNamespace:  "{{ requiredEnv "TILLER_NAMESPACE" }}"
      - project: "{{ requiredEnv "PROJECT" }}"
      - buildNamespace: "{{ requiredEnv "BUILD_NAMESPACE" }}"
      - insecureSkipTlsVerify: {{ env "INSECURE_NO_TLS_VERIFY" | default "false"  }}
      - hooksRelease: {{ env "HOOKS_RELEASE" | default "false"  }}
      - envGitUrl: "{{ requiredEnv "GIT_URL" }}"
      - webhookRepFullname: "{{ requiredEnv "GIT_NAME" }}"
      - webhookRefRegex: "{{ env "WEBHOOK_REF_REGEX" }}"
      - webhookSecret: "{{ env "WEBHOOK_SECRET" }}"
      - env: "{{ requiredEnv "ENV_PREFIX" }}"
      - openshiftServer: "{{ requiredEnv "OPENSHIFT_SERVER" }}"
      - chatbotNotify: "{{ env "CHATBOT_NOTIFY" }}"
      # // use deploy_env for arbitrary env vars in used by you own ocd-pre/post-apply-hook
      # - deploy_env: 
      #   - name: SOMETHING
      #     value: "{{ env "SOME_VALUE" }}"

