repositories:
  - name: ocd-meta 
    url: https://ocd-scm.github.io/ocd-meta/charts
releases:
  - name: {{ requiredEnv "ENV_PREFIX" }}-ocd-credentials
    labels:
      secret: ocd-oc-credentials
    chart: ocd-meta/ocd-secret
    version: ~1.0.0
    values:
      - name: ocd-oc-credentials
      - env_vars: 
        - key: OPENSHIFT_SERVER
          value: "{{ requiredEnv "OPENSHIFT_SERVER" }}"
        - key: OPENSHIFT_USER
          value: "{{ requiredEnv "OPENSHIFT_USER" }}"
        - key: OPENSHIFT_PASSWORD
          value: "{{ requiredEnv "OPENSHIFT_PASSWORD" }}"
  - name: {{ requiredEnv "ENV_PREFIX" }}-ocd-webhook
    labels:
      builder: realworld
    chart: ./ocd-environment-webhook
    version: ~1.1.0
    values:
      - tillerNamespace:  "{{ requiredEnv "TILLER_NAMESPACE" }}"
      - project: "{{ requiredEnv "PROJECT" }}"
      - insecureSkipTlsVerify: {{ env "INSECURE_NO_TLS_VERIFY" | default "false"  }}
      - hooksRelease: {{ env "HOOKS_RELEASE" | default "false"  }}
      - envGitUrl: "{{ requiredEnv "GIT_URL" }}"
      - webhookRepFullname: "{{ requiredEnv "GIT_NAME" }}"
      - webhookRefRegex: "{{ env "WEBHOOK_REF_REGEX" }}"
      - webhookSecret: "{{ env "WEBHOOK_SECRET" }}"
      - env: "{{ env "ENV_PREFIX" }}"

